### ISSUE TITLE
Why test wrong?

### ISSUE THREAD

**Issue by jzhw0130** [tlil/graphql-objc#3]
Hi

Run the test api: testValidQuery, get wrong result:

Test Suite 'Selected tests' started at 2017-05-16 09:31:34.355
Test Suite 'GraphQLTests.xctest' started at 2017-05-16 09:31:34.355
Test Suite 'GraphQLTests' started at 2017-05-16 09:31:34.356
Test Case '-[GraphQLTests testValidQuery]' started.
2017-05-16 09:31:36.577 xctest[51938:3922449] Error: SyntaxError: Unexpected token '>'
2017-05-16 09:31:36.578 xctest[51938:3922449] Error: ReferenceError: Can't find variable: engine
2017-05-16 09:31:36.578 xctest[51938:3922449] Error: ReferenceError: Can't find variable: engine
/Users/jing/Downloads/graphql-objc-master/Example/GraphQLTests/GraphQLTests.m:50: error: -[GraphQLTests testValidQuery] : Asynchronous wait failed: Exceeded timeout of 2 seconds, with unfulfilled expectations: "Successful query".
/Users/jing/Downloads/graphql-objc-master/Example/GraphQLTests/GraphQLTests.m:52: error: -[GraphQLTests testValidQuery] : failed - Query timed out
Test Case '-[GraphQLTests testValidQuery]' failed (6.762 seconds).
Test Suite 'GraphQLTests' failed at 2017-05-16 09:31:41.119.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.762 (6.763) seconds
Test Suite 'GraphQLTests.xctest' failed at 2017-05-16 09:31:41.119.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.762 (6.764) seconds
Test Suite 'Selected tests' failed at 2017-05-16 09:31:41.120.
	 Executed 1 test, with 2 failures (0 unexpected) in 6.762 (6.765) seconds

Test session log:
	/Users/jing/Library/Developer/Xcode/DerivedData/GraphQL-hcnkaaatqrjezqdoywzpxqtrxjuq/Logs/Test/9300851E-E75A-4552-ADB2-9A1DD938F623/Session-GraphQLTests-2017-05-16_093132-yHJ44V.log

Program ended with exit code: 1

Did I do something wrong ?

Thanks

**Comment by tlil** [comment]
Interesting! Can you provide some more context? What version of Xcode, OS, etc.? Seems like `engine.js` throws a syntax error, so I'm wondering if either (1) the file isn't located correctly, or (2) the JS engine on your machine is of an older version.

Can you set a breakpoint on line 22 in `GQLEngine.m` and give me more context from `exception`?
```obj-c
        errorHandler([exception toString]);
```

**Comment by jzhw0130** [comment]
Xcode 8.2.1  
Mac os: 10.11.6
node :  v7.10.0

How to get the version of JS engine? 

I just run the test api :  - (void)testValidQuery

The exception is: 
SyntaxError: Unexpected token '>'  

Thanks

**Comment by tlil** [comment]
Can you set a breakpoint on line 43 in GQLEngine.m:

```obj-c
[self.context evaluateScript:script];
```

and post the content of the variable `script` at that stage here (in an attachment)?

Sorry about that - thanks for your patience whilst I'm trying to figure this out :-)

**Comment by jzhw0130** [comment]
ok

[script-content.zip](https://github.com/tlil/graphql-objc/files/1009499/script-content.zip)

**Comment by tlil** [comment]
Could you try using this `engine.js` file instead of the one that's in the repo now @jzhw0130? It might be the packer/minifier that renders some of the JS invalid for the engine running on older macOS versions...

Attachment: [engine.js.zip](https://github.com/tlil/graphql-objc/files/1009851/engine.js.zip)

**Comment by jzhw0130** [comment]
With the new version of engine.js, also get the exception:

2017-05-18 20:40:25.971 xctest[19229:4597700] Error: SyntaxError: Unexpected token '>'

**Comment by tlil** [comment]
@jzhw0130 Thanks, I've managed to narrow down the problem now on a colleague's laptop, so I will push a fix for the issue soon. Thanks for hanging in there :)

**Comment by tlil** [comment]
@jzhw0130 Can you please test the branch I just put up before I merge it (https://github.com/tlil/graphql-objc/pull/4)? It seems to work fine here now.

**Comment by jzhw0130** [comment]
@tlil 

Thanks
The branch (graphql-objc-ensure-legacy-js-syntax) works well.

Could you tell me the problem?

Jing

**Comment by tlil** [comment]
The problem was that the `engine.js` file was using a newer JS syntax which caused it to trip up. Also, promises are part of the newer JS engine, but weren't supported on El Capitan, so had to import a package and then implement `setTimeout` and related, dependent functions and link those in as well.
